### ISSUE TITLE
Test failures in a job might "shadow" timeouts

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus-github-bot#103]
This happened here: https://github.com/quarkusio/quarkus/pull/16056#issuecomment-840753897 (see also: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/CI.20unstable)

To @loicmathieu (and others) it looked like as if only that one test failed in the Windows job but in fact there was also:
```
 Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project quarkus-integration-test-mongodb-client: There was a timeout in the fork -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project quarkus-integration-test-mongodb-client: There was a timeout in the fork
```
and
```
 Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project quarkus-integration-test-mongodb-panache: There was a timeout in the fork -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project quarkus-integration-test-mongodb-panache: There was a timeout in the fork
```
(which are both printed at the very end, due to `--fail-at-end`).

So it seems we need more logfile analysis by the bot.

Spitballing ideas:
- Check for a `.dump` file in each surefire archive which should only be present if something was wrong, e.g. `2021-05-13T15-30-11_117-jvmRun1.dump` from `mongodb-client`:
  ```
  # Created at 2021-05-13T17:57:19.395
  Killing self fork JVM. Received SHUTDOWN command from Maven shutdown hook.
  Thread dump before killing the process (6304@fv-az159-945):
  "main" 
     java.lang.Thread.State: RUNNABLE
  [...]
  ```
- or parse the build summary for ` FAILURE `:
  ```
  [...]
  2021-05-13T18:35:40.4533500Z [INFO] Quarkus - Integration Tests - MongoDB Client ....... FAILURE [10:04 min]
  2021-05-13T18:35:40.4534433Z [INFO] Quarkus - Integration Tests - Jackson .............. SUCCESS [ 21.107 s]
  [...]
  2021-05-13T18:35:40.4697795Z [INFO] Quarkus - Integration Tests - Kotlin ............... SUCCESS [02:12 min]
  2021-05-13T18:35:40.4727223Z [INFO] Quarkus - Integration Tests - MongoDB Panache ...... FAILURE [10:06 min]
  [...]
  ```
- or introduce a Maven extension that writes failures to a log file that can be picked up by the bot
  Integration point would be https://maven.apache.org/ref/3-LATEST/maven-core/apidocs/org/apache/maven/execution/MojoExecutionListener.html (/cc @aloubyansky)
- ...?

**Comment by gsmet** [comment]
@famod do you know how to generate a dump file (e.g. to reproduce the issue and see how we can take it into account)?

**Comment by famod** [comment]
I guess setting something like `-Dsurefire.timeout=1` should work.

**Comment by gsmet** [comment]
OK. Analyzing the log could be a good idea too but we would need to map the test failures to the name of the modules. No idea if the info is easily available.

**Comment by famod** [comment]
I think the Maven extension would be the most comprehensive solution but also the most labor-intensive one.

**Comment by gsmet** [comment]
I think we could develop a Maven extension following these principles:
- based on https://maven.apache.org/examples/maven-3-lifecycle-extensions.html
- implementing `afterSessionEnd`
- getting the `MavenExecutionResult` from the `MavenSession`
- get the list of projects via `getTopologicallySortedProjects`
- for each project, get the build summary (`getBuildSummary`), and depending of if it's a `BuildFailure` or `BuildSuccess` (test using `instanceof`), write the result in a JSON file (we need to include the throwable information in case it's defined) in the `target/` directory. Writing to a JSON file should use a `List<ProjectBuildResult>` with `ProjectBuildResult` being a simple Java POJO we initialize and we will use Jackson to write this to a file.

We will need to experiment a bit with a multi-module Maven project with the different situations:
- build success
- build failure with a test failing
- build failure with something else (surefire.timeout like above, a formatting error could also be a good example - e.g. set up the formatter plugin as in quarkus-github-bot, introduce a formatting error and run with `-Dno-format` to trigger the error).

**Comment by famod** [comment]
@gsmet this is covered by https://github.com/quarkusio/build-reporting-maven-extension for a while now, right?

**Comment by gsmet** [comment]
Yes.
