### ISSUE TITLE
Avoid links to zulip chat in PRs/Issues

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus-github-bot#113]
## Description

As pointed out by Thomas Wuerthinger in https://github.com/oracle/graal/discussions/3477#discussioncomment-889548 getting access to the zulip chat logs requires setting up an account and logging in. PR/Issue descriptions/discussions should be self-contained or only link to publicly accessible info (without requiring logging in to a service to get access). As a result, links to any zulip chat messages should only be complementary and a summary of what's been told in the chat should be provided in the PR/Issue description.

## Implementation ideas

To automate this we could use a bot checking for zulip references in PR/Issue descriptions.

**Comment by gsmet** [comment]
We need something similar to https://github.com/quarkusio/quarkus-bot/blob/main/src/main/java/io/quarkus/bot/CheckPullRequestEditorialRules.java but for issues.

And we need to look for links like `https://quarkusio.zulipchat.com/#narrow/stream/187038-dev` so basically anything starting with https://quarkusio.zulipchat.com/ .

**Comment by maxandersen** [comment]
we could even consider something like https://github.com/zulip/zulip-archive that apparently can archive zulip chats.

**Comment by maxandersen** [comment]
https://github.com/zulip/zulip/issues/4817 has lots of interesting conversation around this.

**Comment by gsmet** [comment]
I don't think it's a good idea. An issue should contain all the information.

**Comment by maxandersen** [comment]
@gsmet sorry if i was unclear - didn't mean to say an issue shouldn't have all the info; I definitely think it should including links to zulip topics - but instead of password protected log have zulip archive published.

are you suggesting issues should not link to zulip at all? 

p.s. i'm running an initial archiving of our zulip to see how it will actually work if we did it.

**Comment by gsmet** [comment]
> are you suggesting issues should not link to zulip at all?

Yes, exactly. It makes searching for issues harder as you don't have the full content in the issue. Sometimes it might make sense to link to the Zulip discussion anyway but we definitely need to avoid "Please fix the issue I reported on Zulip: <link to Zulip discussion>". We had a few reports like that (or pointing to a random pastebin for the details).

So what I would do would be to just add a comment with something like "You included a Zulip link, make sure the issue description contain all the necessary information to understand the problem."

**Comment by maxandersen** [comment]
Ack. So we agree.  Having bot give a friendly reminder :)
