### ISSUE TITLE
Block Merge if there are merge commits in the PR

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-github-bot#119]
See for instance https://github.com/quarkusio/quarkus/pull/17765/commits .

Merge commits are a pain when we have to cherry-pick a PR to a maintenance branch so we'd better avoid them.

We should add a check on opened and synchronize to check if there are merge commits. I'm not sure if the GH API contains the information or if we will have to limit ourselves to checking the title of the commit.

**Comment by famod** [comment]
The GH feature doesn't work here?
![lin-hist](https://user-images.githubusercontent.com/22860528/131564888-60fc4a56-8cb3-4f42-8ad3-4895a2941c33.png)

**Comment by nicolasgras** [comment]
Hi @gsmet, could not this issue be closed as #236 is closed now?

**Comment by gsmet** [comment]
Sure, thanks!
