### ISSUE TITLE
Don't cc maintainer(s) when already participating

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus-github-bot#143]
When I replace the needs-triage label with the respective area label, the bot is /cc-ing the respective maintainer(s) (if any), which is totally fine and helpful.
More more often than not, people have already started commenting an issue without replacing the needs-triage label and so they are faced with needless spam when the label is replaced later on.

It would be nice if the bot could check the participants before adding the cc comment.

**Comment by gsmet** [comment]
I think we just need to check the first page of comments (maybe the first 20) and collect the authors. We don't need (and should avoid) to get all the issues.
