### ISSUE TITLE
Support `@quarkusbot rebase` command

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus-github-bot#23]
It would be nice if one could do `@quarkusbot rebase` and have Quarkus bot to automatically rebase any PR (like `@dependabot rebase` does)

**Comment by gsmet** [comment]
hey @gastaldi , you mentioned you had a working prototype for this one? @Luke1432 will be joining us for a month soon and maybe he could help finalizing this.

**Comment by gastaldi** [comment]
@gsmet I had but I just noticed that I discarded when I re-checked out the sources 😞 

What I did in the bot was to:

1) Clone the main repository branch.
2) Listen for merges to the main branch and update the working copy locally
3) When the `@quarkusbot rebase` command is issued, the PR would rebase against this local working copy and force-push

Obviously that would fail if the PR had conflicts.

**Comment by gastaldi** [comment]
This is already supported in GitHub UI. Closing now
