### ISSUE TITLE
Integrate the duplicate workflow run cancellation to the bot

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-github-bot#25]
Right now, we have a GitHub Action running as a cronjob using https://github.com/n1hility/cancel-previous-runs . Which works quite well... until we don't have any available spot for action execution: then the PRs are not cancelled anymore. And it's typically when we are in this situation that this is the most useful.

@famod also pointed out this GH Action: https://github.com/fkirc/skip-duplicate-actions

It has the same issue as our original approach though.

Doing this with the bot would avoid all these issues. We can base the bot rule on the already existing code.

**Comment by famod** [comment]
FTR, as discussed [here](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/CI.3A.20broken.20master.20shadowing.20problem), what is currently being considered "duplicate" can be very different things. E.g. a Doc-only run can cancel a previously started full CI run and you end up with certain code changes in `main` that have never passed the full CI.

As a first step, the bot could try to detect that and only cancel a full CI run in case the newer run is a full CI run as well.
But this would imply that people have to start caring not only for the latest build result. Not sure this is realistic.

But in the end, this really is a limitation of GH's workflow mechanics.

**Comment by gsmet** [comment]
The bot only cancels workflow runs that share the same workflow. So a Quarkus CI run will not cancel a Quarkus doc run.

**Comment by gsmet** [comment]
Implemented in https://github.com/quarkusio/quarkus-bot/pull/72 .

**Comment by famod** [comment]
Nice! So we can drop those `cancel-previous-runs` actions?
(Hm, maybe not for PRs?)
