### ISSUE TITLE
Show the test method that failed

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus-github-bot#61]
It would be nice if the bot could show the test method that failed next to the failed test:

Here is an example of the actual feedback. It´s not possible to know which test failed unless you click on the sources: 

![image](https://user-images.githubusercontent.com/54133/114272567-1b584280-99ed-11eb-97a0-a7a82e0f1ce6.png)

**Comment by gsmet** [comment]
I totally missed the info was available. https://github.com/quarkusio/quarkus-bot/pull/62 should fix it.
