### ISSUE TITLE
Cancel workflow when a PR is closed or merged

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-github-bot#80]
We sometimes merge PRs because CI is irrelevant and we also close PRs that are invalid. We should cancel any running workflow run in this case.

**Comment by famod** [comment]
Hm, I was under the impression that GH ìs doing that by default?

**Comment by gsmet** [comment]
No it doesn't. At least not the last time I checked.

**Comment by famod** [comment]
Ah, yes - just had this in my fork with one of those dependabot PRs (which are really getting on my nerves).

**Comment by gsmet** [comment]
Hint: you can get a workflow run with the head branch from the PR but you will also need to check that the head repository in the workflow run is equal to the head repository of the PR.

BTW, maybe it would be worth testing  if the GitHub API supports a branch in the user:branch format when searching for workflow runs as it would simplify things a bit.

**Comment by gsmet** [comment]
@glefloch if you want to have a look at something a bit more complicated, this one would be a good one. 

This workflow https://github.com/gsmet/quarkus-bot-java-playground/pull/59/files#diff-ff8aecb4342af4f777680b404adda6fd8a6d0d0e384525839691d158032ab6c5 is handy to test this sort of things.

**Comment by gsmet** [comment]
Note that the event for merges is also the close event so it's the one that should be listened to.

**Comment by glefloch** [comment]
Yes definitely interested on this one too.
