### ISSUE TITLE
 use no-response bot or implement similar ?

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus-github-bot#81]
on [zulip](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Qurkus.20bot.20close.2Fopen.20for.20feedback.20feature.20.3F) I suggested the following:

we didn't like stalebot approach to try help reduce number of irrelevant issues to stay open. I saw a different approach in rambox issue tracker. They have a bot that closes issues marked with I.e "need more info" and then closes it if doesn't get more info added after a few days. If someone does add info, the issue is opened and label removed.

Example: https://github.com/ramboxapp/community-edition/issues/2965

suggestion is to implement it similar to https://github.com/probot/no-response or simply reuse it.

**Comment by gsmet** [comment]
I think what @yrodiere implemented with the lottery is a good alternative.
