### ISSUE TITLE
Job status summary: purposely skipped step is reported instead of actual failing one

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus-github-bot#82]
E.g.: https://github.com/quarkusio/quarkus/pull/16529#issuecomment-820583895

![summary](https://user-images.githubusercontent.com/22860528/115141923-33f4d800-a03f-11eb-8111-bc9a91abae66.png)

![steps](https://user-images.githubusercontent.com/22860528/115141997-a2d23100-a03f-11eb-8e2d-8ec49d4c23fe.png)

The step `Verify dependencies` is skipped on purpose on Windows. The actual problem here is `Build with Maven` that was _cancelled_ (due to timeout).
I don't have a link to an example right now but IIRC I've also seen this when `Build with Maven` _failed_ (red status, not cancelled).

**Comment by gsmet** [comment]
Ah yeah, good catch, it's an easy fix.
