### ISSUE TITLE
Also collect Gradle test failures

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus-github-bot#83]
The actual location in Quarkus main should be:
```
integration-tests/gradle/build/test-results/test/
```
Some thing like `**/build/test-results/test/TEST-*.xml` should catch them.

The first thing that needs to be done is to extend the `Upload Surefire reports` step but I suppose something needs to be done in the bot as well?

**Comment by famod** [comment]
For `cancelled` I think we'll also need to add ` || cancelled()` to the `if` condition: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions

**Comment by gsmet** [comment]
Isn't it already handled?

https://github.com/quarkusio/quarkus/blob/main/.github/workflows/ci-actions-incremental.yml#L473
https://github.com/quarkusio/quarkus-bot/blob/main/src/main/java/io/quarkus/bot/workflow/SurefireReportsUnarchiver.java#L22

**Comment by famod** [comment]
Good point! I'll try it out.

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/pull/16251#issuecomment-821954034 for an example of it working.

**Comment by famod** [comment]
Ah, ok. So I guess the only blind spot is cancelled build steps for which the surefire reports are not uploaded yet.
We can adjust that in the main repo without touching the bot.
