### ISSUE TITLE
Check that PRs does not have more than 1 commit

### ISSUE THREAD

**Issue by glefloch** [quarkusio/quarkus-github-bot#96]
As for the Pull request title, we could add a check on the number of commits. If there is more than one commit, we could add a comment to warn about it.

**Comment by gsmet** [comment]
Well having several commits is not a problem per se. What we want is semantic commits. It can make perfect sense to have a PR with several commits.

I think the only things we should warn about are merge commits and fix up commits but I think it would probably be better as a check than as a comment.

Yoann used checks here: https://github.com/hibernate/hibernate-github-bot
