### ISSUE TITLE
More neutral icon for skipped jobs (or don't list them at all)

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus-github-bot#97]
https://github.com/quarkusio/quarkus/pull/16971#issuecomment-832156428

Those red crossed out signs look like failures but they are not.
We will see those more often now that my PR is merged that skips most jobs on purpose when they are not affected by changes.

I suggest to use a more neutral greyish version.

**Comment by gsmet** [comment]
Yeah I wanted that but I haven't found one: https://gist.github.com/rxaviers/7360908 (neither here nor in Unicode). Maybe another symbol would make sense?

The other option would be to use the octicons they use in their table but... it takes a lot more characters and we are very limited.

That being said, now that skipped is a normal behavior, I wonder if we should display them at all.

**Comment by famod** [comment]
> Maybe another symbol would make sense?

🙈? jk! Nah...no good alternative AFAICS.

>  I wonder if we should display them at all.

Very good point! I think this is the best solution.
You can always have a look at the actual workflow summary in case you are interested in skipped jobs.
