### ISSUE TITLE
Make cancellation message after push less scary

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus-github-bot#98]
https://github.com/quarkusio/quarkus/pull/16980#issuecomment-832227552

I wonder if the bot could detect that the workflow was cancelled due to a (another) push and make the message look less "scary".

**Comment by famod** [comment]
...or even don't post a message at all.

**Comment by gsmet** [comment]
I had a look at this one and... the `sender` is the user who pushed the changes not the bot itself so I have no idea who/what cancelled the workflow.

So basically we have two options:
- do not post a comment at all when cancelled
- keep the current behavior

**Comment by famod** [comment]
Just spitballing: The bot knows the branch, no?
Couldn't it compare the sha of the current HEAD of the branch to the sha that triggered the workflow run?

**Comment by gsmet** [comment]
These messages should be gone now... but I think I saw one popping so I wonder if there isn't some sort of weird corner case... Let's see how it goes and reopen if necessary.
